### ISSUE TITLE
recruit AI

### ISSUE THREAD

**Issue by jus61** [GreuhZbug/greuh_liberation.Altis#40] opened 2015-10-23 14:35 UTC
when I recruit AI and then die, I have no more control over the troops

**Comment by GreuhZbug** [comment] 2015-10-23 17:00
It works on my side, could you please provide more precise steps to reproduce the issue

**Comment by GreuhZbug** [comment] 2015-10-26 18:10
Couldn't reproduce in the latest version and no more news -> closing

**Closed as completed by GreuhZbug** 2015-10-26 18:10 UTC
